### PR TITLE
Enhancement - Add transparency slider

### PR DESCRIPTION
**Pull request by AeroSD24**

### CODE REVIEW

**Review by aidenbok203 — APPROVED** [review]

**Comment by AeroSD24** [comment]
auto compile faster pls

**Review by aidenbok203 — APPROVED** [review]

**Review by awdev1 — APPROVED** [review]
LGTM

**Review by aidenbok203 — APPROVED** [review]

**Comment by aidenbok203** [comment]
cancled

**Comment by awdev1** [comment]
Canceled- to save my minutes and to escape form aiden's torture chamber

**Pull request merged**
